[Html to Design] -> [UI Graphics]
bradtraversy/design-resources-for-developers pull request #1221
Opened 2023-01-07 05:47 UTC by devIbtihadj

https://www.figma.com/community/plugin/1159123024924461424/html.to.design

2023-01-07 13:45 UTC, Alaev requested changes
Please remove .idea folder and if you can add the resource without linting the file.

2023-01-08 15:14 UTC, devIbtihadj commented
done

2023-01-08 16:52 UTC, Alaev commented on readme.md
> +| [Github profile readme generator](https://rahuldkjain.github.io/gh-profile-readme-generator/) | Allow you to generate a github profile reamdme. |
Please add resource one in a separate PR.

2023-01-08 16:54 UTC, Alaev requested changes
Please see comment.

2023-01-08 17:44 UTC, devIbtihadj commented
Ok, i think it is ok now, you can check it

2023-01-08 20:49 UTC, Alaev approved these changes

2023-01-08 20:49 UTC, merged