Added libreoffice draw to downloadable design software in readme.md
bradtraversy/design-resources-for-developers pull request #1269
Opened 2023-04-06 23:39 UTC by saberelbah

I added libreoffice draw software to downloadable design software in readme.md

2023-04-06 23:55 UTC, saberelbah reviewed
Okay cool

2023-04-08 13:48 UTC, Alaev requested changes

2023-04-08 13:48 UTC, Alaev commented on readme.md
> +| [Wings 3D](http://www.wings3d.com/) | Wings 3D is a subdivision modeler inspired by Nendo and Mirai from Izware. It is possible to assign materials, vertex color, UV coordinates and textures, but t
Please unlint the top portion of the file and if you can please one PR per resource :)

2023-04-20 11:32 UTC, Alaev commented
Closing in active.

2023-04-20 11:32 UTC, closed without merging