[Colorlab] -> [Colors]
bradtraversy/design-resources-for-developers pull request #1413
Opened 2024-07-12 16:21 UTC by lovatom

Link: https://getcolorlab.com/

# Resource Name - Colorlab

Colorlab is an online tool to create color palettes, gradients, color scales, check color contrast.

Link: www.getcolorlab.com

#### Checklist:

- [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

2024-07-18 15:53 UTC, StefanSelfTaught requested changes
Leave the `pull_request_template.md` file as it is.

2024-07-24 13:10 UTC, Alaev requested changes

2024-07-24 13:10 UTC, Alaev commented on .github/pull_request_template.md
Please revert this file. 

no need to modify it.

2024-07-24 14:14 UTC, lovatom commented
sorry for the misunderstanding guys! Just did a commit to revert that change.

2024-07-24 22:21 UTC, Alaev approved these changes

2024-07-24 22:21 UTC, merged