add simpleparallax a tiny Vanilla JS
bradtraversy/design-resources-for-developers pull request #833
Opened 2021-05-01 18:15 UTC by fahimfaisaal

**Please delete this line before submitting**, _Pull request TITLE should look like this_: `[Resource] -> [Resource Section In Docs]`

# Resource Name - Edit this line

Edit this line with Small Description about new added resource

Link: www.linkToResource

#### Checklist:

- [ ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

2021-05-01 19:01 UTC, Alaev requested changes

2021-05-01 19:01 UTC, Alaev commented on readme.md
> +| [Simple Parallax](https://simpleparallax.com/)| he easiest way to get a parallax effect with javascript |
Should it say "The"?

2021-05-02 10:40 UTC, fahimfaisaal commented on readme.md
> +| [Simple Parallax](https://simpleparallax.com/)| he easiest way to get a parallax effect with javascript |
oops, yes. sorry for my silly mistake.

2021-05-02 10:43 UTC, fahimfaisaal reviewed
have fixed the spelling

2021-05-03 10:48 UTC, merged