Added Materio Free Vuetify Vuejs Admin Template
bradtraversy/design-resources-for-developers pull request #948
Opened 2021-08-24 11:34 UTC by saanvi-ts

`[Materio Free Vuetify Vuejs Admin Template] -> [Vue UI]`

# Materio Free Vuetify Vuejs Admin Template

**Materio Free VueJS Vuetify Admin Dashboard Template** – is the latest most developer-friendly 🤘🏻 & highly customizable✨ Admin Dashboard Template based on Vuetify. If you’re a developer looking for a Vuejs Admin Template enriched with features and a highly customizable look no further than Materio Free Vuetify Vuejs admin template🤩 . Besides, the highest industry standards are considered to bring you the very best Vuetify admin template that is not just fast🚀and easy to use, but highly scalable. Offering ultimate convenience and flexibility, you’ll be able to build whatever application you want without any hassle.

Furthermore, you can use this one of the best innovative free Vuejs admin templates to create eye-catching, high-quality, and high-performing single-page applications. Besides, your apps will be completely responsive, ensuring they’ll look stunning and function flawlessly on desktops, tablets, and mobile devices.

**Features:**

- 1 Simple Dashboard, 1 Chart Library
- Single vertical menu
- Simple Light/Dark theme
- Basic Cards, pages, and tables
- Simple From Elements⚡
- Single vertical menu

Link:
Demo: https://themeselection.com/demo/materio-vuetify-vuejs-admin-template-free/demo/dashboard
GitHub: https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free

2021-08-24 12:06 UTC, Alaev requested changes

2021-08-24 12:06 UTC, Alaev commented on readme.md
> +| [Materio Free Vuetify Vuejs Admin Template](https://themeselection.com/products/materio-free-vuetify-vuejs-admin-template/)| Open-source & Easy to use 🤩 Vuetify Vuejs Admin Template with Elegant De
Please rename to [Materio Vuetify Vuejs Admin Template], no need for the keyword free.

Please remove emoji icon 🤩

2021-08-24 15:17 UTC, Alaev approved these changes

2021-08-24 15:19 UTC, merged

2021-08-25 05:13 UTC, saanvi-ts commented
Thank you very much for adding Materio.